### ISSUE TITLE
Establish project guidlines

### ISSUE THREAD

**Issue by jonasjonker** [jonasjonker/sleep-deprivation#2]
This project just started. I think it is a good idea to agree on some basic project guidlines.

I don't think we need to agree on things like a project structure (yet), but we could think about it if the project turns out to be quit big or if enough people think that's a good idea.

**Comment by laurabog** [comment]
Sounds good! So anything specific to discuss now?

**Comment by jonasjonker** [comment]
Well, if everybody agrees with what i wrote in the README than there is not much to discuss :)
